channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.3.0
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
